apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: servicio-prueba
  name: servicio-prueba
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: servicio-prueba
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: servicio-prueba
    spec:
      containers:
        - image: danielcollaguazo/servicio-prueba
          name: servicio-prueba
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9990
              protocol: TCP
      restartPolicy: Always
